# 1. SECRETS (Store securely, NEVER commit real values to git)
# Use `kubectl create secret generic` or sealed-secrets
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: shopsphere
type: Opaque
stringData:
  mongo-root-username: admin
  mongo-root-password: admin12345
  mongo-express-username: admin
  mongo-express-password: express-pass
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: shopsphere
type: Opaque
stringData:
  jwt-secret: your_strong_secret_key_here_change_me
  mongo-uri: mongodb://admin:admin12345@mongo.shopsphere.svc.cluster.local:27017/shopsphereDB?authSource=admin