apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  mongo-database: shopsphereDB
  port: "5000"
  cors-origin: "*"
  mongo-auth-source: admin
  node-env: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: shopsphere
data:
  mongo-image: mongo:6.0
  storage-size: 5Gi