apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to shared base
resources:
  - ../../base

# Optional: Apply name prefix/suffix
nameSuffix: -prod

namePrefix: app1-

labels:
  - pairs:
      env: prod
    includeSelectors: true

images:
- name: nginx # Will look for container with image name nginx
  newName: nginx
  newTag: "1.22"

commonAnnotations:
  branch: prod
  support: 800-800

namespace: prod

replicas:
- name: nginx-deploy
  count: 5